### ISSUE TITLE
Can not run in vs code, and instructions not clear enough

### ISSUE THREAD

**Issue by ucanzeee** [doomsower/react-native-startup-time#11]
I tried everything but this just doesn't work. Your docs isn't very clear. No good example aswell. Tried putting that function into a variable but it doesn't work. Console log doesn't work. Nothing works. I literally wasted a lot of time with this.

**Comment by doomsower** [comment]
I don't feel like I need to add anything to docs. The package is small enough to figure everything out from the code. 
The example is literally 3 lines of code: one in package.json, one import and one component. If you think the package itself is broken (maybe with latest RN), then please open new issue with reproduction or at least some useful feedback.
