### ISSUE TITLE
Issue with Android KitKat

### ISSUE THREAD

**Issue by johanblomgren** [doomsower/react-native-startup-time#6]
Hi! 
We tried out the package while implementing performance instrumentation but ran into issues with the following exception:
`uid xxxxx does not have android.permission.UPDATE_DEVICE_STATS.`

Affected OS versions seem to be `KitKat` (as has been reported by other users of `reportFullyDrawn()`) and when going through the implementation, I noticed the check for that specific range of versions. However, the check seem to _include_ `KitKat` - should it not be
```>= Build.VERSION_CODES.LOLLIPOP```
instead?

Thanks in advance!

**Comment by doomsower** [comment]
Thank you. I've published new version where this issue is fixed.
